### ISSUE TITLE
letsencrypt ssl not setup for WAGTAIL_HOST

### ISSUE THREAD

**Issue by GuilhermeBCM** [murat-polat/tutor-wagtail#2]
Hello!

I am trying the wagtail plugin to my ssl-enabled tutor, version 10.2.2.
SSL certificates were setup for every FQDN, but for the new one needed for WAGTAIL_HOST it is not setup, and breaks nginx_1 trying to start and not finding the certificate.
I have tried "tutor local https create" and it is not aware of WAGTAIL_HOST.
Then I had to "tutor plugins disable wagtail; tutor config save; tutor local reboot" to bring system back online with no tutor-wagtail.

Please let me know it need more details. It is not yet a production environment and I can do more tests/collects.

Thanks and Kind Regards,
Guilherme

**Comment by GuilhermeBCM** [comment]
The https-create patch fixed the certificate issue for me.

**Comment by murat-polat** [comment]
@GuilhermeBCM   Thank you very much, for contributions  👍
